Update run.sh
FFY00/build-arch-package pull request #2
Opened 2020-12-28 10:08 UTC by taotieren

2020-12-28 17:55 UTC, FFY00 requested changes
Hi, thank you!

Could you split the changes into two commits, one for the source copy and one for the build script input?
Could you also rename the `BUILDING` input to `BUILD_SCRIPT`?

If you do not want, or are too busy, to do it I can do it myself :blush:

2020-12-29 05:37 UTC, taotieren commented
You can fix this. Thanks

2022-03-28 21:17 UTC, ljmf00 commented
Source copy was addressed by https://github.com/FFY00/build-arch-package/pull/3 . I can reboot this if you want @FFY00 .

2022-03-28 21:47 UTC, FFY00 commented
Yes, please, I totally forgot this :disappointed:

2022-03-29 16:45 UTC, ljmf00 commented
I renamed the argument as requested and made it `BUILD_SCRIPT` optional rather than required, for backward compatibility. Updated the added table with the required alignment.

2022-03-29 16:58 UTC, FFY00 approved these changes
Thanks!

2022-03-29 16:58 UTC, merged